package com.hutuneko.psi_ex.datagen;

public class Set {
    public static final String[] PSI_PIECES = {
            "trick_conjure_block_sequence",
            "trick_mass_add_motion",
            "trick_place_in_sequence",
            "trick_move_block",
            "trick_night_vision",
            "trick_eidos_anchor",
            "trick_till_sequence",
            "trick_conjure_light",
            "trick_smelt_item",
            "trick_delay",
            "trick_play_sound",
            "trick_collapse_block",
            "trick_conjure_block",
            "trick_break_in_sequence",
            "trick_break_loop",
            "trick_fire_resistance",
            "trick_save_vector",
            "trick_resistance",
            "trick_place_block",
            "trick_overgrow",
            "trick_ignite",
            "trick_break_block",
            "trick_blaze",
            "trick_collapse_block_sequence",
            "trick_mass_exodus",
            "trick_torrent",
            "trick_die",
            "trick_water_breathing",
            "trick_add_motion",
            "trick_regeneration",
            "trick_haste",
            "trick_move_block_sequence",
            "trick_till",
            "trick_jump_boost",
            "trick_smite",
            "trick_mass_blink",
            "trick_switch_target_slot",
            "trick_strength",
            "trick_invisibility",
            "trick_smelt_block_sequence",
            "trick_weakness",
            "trick_particle_trail",
            "trick_infusion",
            "trick_russian_roulette",
            "trick_change_slot",
            "trick_speed",
            "trick_eidos_reversal",
            "trick_slowness",
            "trick_wither",
            "trick_evaluate",
            "trick_explode",
            "trick_smelt_block",
            "trick_blink",
            "trick_spin_chamber",
            "trick_detonate",
            "trick_greater_infusion",
            "trick_ebony_ivory"
    };

    public static final String[] PSI_EX_PIECES = {
            "coordinate_eidos_renewal"
    };
}
